-- Convert WorkerProfile.specialties from display strings to slug IDs
UPDATE "WorkerProfile"
SET specialties = ARRAY(
  SELECT CASE value
    WHEN 'Knotless braids' THEN 'knotless-braids'
    WHEN 'Box braids'      THEN 'box-braids'
    WHEN 'Feed-in braids'  THEN 'feed-in-braids'
    WHEN 'Cornrows'        THEN 'cornrows'
    WHEN 'Locs'            THEN 'locs'
    WHEN 'Faux locs'       THEN 'faux-locs'
    WHEN 'Loc maintenance' THEN 'loc-maintenance'
    WHEN 'Natural hair'    THEN 'natural-hair'
    WHEN 'Blowout'         THEN 'blowout'
    WHEN 'Silk press'      THEN 'silk-press'
    WHEN 'Relaxer'         THEN 'relaxer'
    WHEN 'Color'           THEN 'color'
    WHEN 'Balayage'        THEN 'balayage'
    WHEN 'Highlights'      THEN 'highlights'
    WHEN 'Weave/Sew-in'   THEN 'weave-sew-in'
    WHEN 'Wigs'            THEN 'wigs'
    WHEN 'Wig install'     THEN 'wig-install'
    WHEN 'Extensions'      THEN 'extensions'
    WHEN 'Twists'          THEN 'twists'
    WHEN 'Twist out'       THEN 'twist-out'
    WHEN 'Bantu knots'     THEN 'bantu-knots'
    WHEN 'Crochet braids'  THEN 'crochet-braids'
    WHEN 'Frontal sew-in'  THEN 'frontal-sew-in'
    WHEN 'Quick weave'     THEN 'quick-weave'
    WHEN 'Curly cut'       THEN 'curly-cut'
    WHEN 'Vivid color'     THEN 'vivid-color'
    WHEN 'Gel nails'       THEN 'gel-nails'
    WHEN 'Acrylic nails'   THEN 'acrylic-nails'
    WHEN 'Nail art'        THEN 'nail-art'
    WHEN 'Dip powder'      THEN 'dip-powder'
    WHEN 'Press-on nails'  THEN 'press-on-nails'
    WHEN 'Pedicure'        THEN 'pedicure'
    WHEN 'Manicure'        THEN 'manicure'
    WHEN 'Nail repair'     THEN 'nail-repair'
    WHEN 'Classic lashes'  THEN 'classic-lashes'
    WHEN 'Volume lashes'   THEN 'volume-lashes'
    WHEN 'Hybrid lashes'   THEN 'hybrid-lashes'
    WHEN 'Lash lift'       THEN 'lash-lift'
    WHEN 'Lash tint'       THEN 'lash-tint'
    WHEN 'Mega volume'     THEN 'mega-volume'
    WHEN 'Bridal makeup'   THEN 'bridal-makeup'
    WHEN 'Editorial makeup'THEN 'editorial-makeup'
    WHEN 'Airbrush makeup' THEN 'airbrush-makeup'
    WHEN 'Event makeup'    THEN 'event-makeup'
    WHEN 'Natural makeup'  THEN 'natural-makeup'
    WHEN 'Glam makeup'     THEN 'glam-makeup'
    WHEN 'SFX'             THEN 'sfx'
    WHEN 'Skin fade'       THEN 'fades'
    WHEN 'Fades'           THEN 'fades'
    WHEN 'Taper fade'      THEN 'taper-fade'
    WHEN 'Lineups'         THEN 'lineups'
    WHEN 'Beard trim'      THEN 'beard-trim'
    WHEN 'Beard design'    THEN 'beard-design'
    WHEN 'Kids cuts'       THEN 'kids-cuts'
    WHEN 'Hair coloring'   THEN 'hair-coloring'
    WHEN 'Hot towel shave' THEN 'hot-towel-shave'
    WHEN 'Facials'         THEN 'facials'
    WHEN 'Waxing'          THEN 'waxing'
    WHEN 'Threading'       THEN 'threading'
    WHEN 'Chemical peels'  THEN 'chemical-peels'
    WHEN 'Microdermabrasion' THEN 'microdermabrasion'
    WHEN 'Lash brows'      THEN 'lash-brows'
    WHEN 'Brow lamination' THEN 'brow-lamination'
    ELSE lower(regexp_replace(value, '[^a-zA-Z0-9]+', '-', 'g'))
  END
  FROM unnest(specialties) AS value
)
WHERE cardinality(specialties) > 0;

-- Convert SalonProfile.specialties from display strings to slug IDs
UPDATE "SalonProfile"
SET specialties = ARRAY(
  SELECT CASE value
    WHEN 'Knotless braids' THEN 'knotless-braids'
    WHEN 'Box braids'      THEN 'box-braids'
    WHEN 'Feed-in braids'  THEN 'feed-in-braids'
    WHEN 'Cornrows'        THEN 'cornrows'
    WHEN 'Locs'            THEN 'locs'
    WHEN 'Faux locs'       THEN 'faux-locs'
    WHEN 'Loc maintenance' THEN 'loc-maintenance'
    WHEN 'Natural hair'    THEN 'natural-hair'
    WHEN 'Blowout'         THEN 'blowout'
    WHEN 'Silk press'      THEN 'silk-press'
    WHEN 'Relaxer'         THEN 'relaxer'
    WHEN 'Color'           THEN 'color'
    WHEN 'Balayage'        THEN 'balayage'
    WHEN 'Highlights'      THEN 'highlights'
    WHEN 'Weave/Sew-in'   THEN 'weave-sew-in'
    WHEN 'Wigs'            THEN 'wigs'
    WHEN 'Wig install'     THEN 'wig-install'
    WHEN 'Extensions'      THEN 'extensions'
    WHEN 'Twists'          THEN 'twists'
    WHEN 'Twist out'       THEN 'twist-out'
    WHEN 'Bantu knots'     THEN 'bantu-knots'
    WHEN 'Crochet braids'  THEN 'crochet-braids'
    WHEN 'Frontal sew-in'  THEN 'frontal-sew-in'
    WHEN 'Quick weave'     THEN 'quick-weave'
    WHEN 'Curly cut'       THEN 'curly-cut'
    WHEN 'Vivid color'     THEN 'vivid-color'
    WHEN 'Gel nails'       THEN 'gel-nails'
    WHEN 'Acrylic nails'   THEN 'acrylic-nails'
    WHEN 'Nail art'        THEN 'nail-art'
    WHEN 'Dip powder'      THEN 'dip-powder'
    WHEN 'Press-on nails'  THEN 'press-on-nails'
    WHEN 'Pedicure'        THEN 'pedicure'
    WHEN 'Manicure'        THEN 'manicure'
    WHEN 'Nail repair'     THEN 'nail-repair'
    WHEN 'Classic lashes'  THEN 'classic-lashes'
    WHEN 'Volume lashes'   THEN 'volume-lashes'
    WHEN 'Hybrid lashes'   THEN 'hybrid-lashes'
    WHEN 'Lash lift'       THEN 'lash-lift'
    WHEN 'Lash tint'       THEN 'lash-tint'
    WHEN 'Mega volume'     THEN 'mega-volume'
    WHEN 'Bridal makeup'   THEN 'bridal-makeup'
    WHEN 'Editorial makeup'THEN 'editorial-makeup'
    WHEN 'Airbrush makeup' THEN 'airbrush-makeup'
    WHEN 'Event makeup'    THEN 'event-makeup'
    WHEN 'Natural makeup'  THEN 'natural-makeup'
    WHEN 'Glam makeup'     THEN 'glam-makeup'
    WHEN 'SFX'             THEN 'sfx'
    WHEN 'Skin fade'       THEN 'fades'
    WHEN 'Fades'           THEN 'fades'
    WHEN 'Taper fade'      THEN 'taper-fade'
    WHEN 'Lineups'         THEN 'lineups'
    WHEN 'Beard trim'      THEN 'beard-trim'
    WHEN 'Beard design'    THEN 'beard-design'
    WHEN 'Kids cuts'       THEN 'kids-cuts'
    WHEN 'Hair coloring'   THEN 'hair-coloring'
    WHEN 'Hot towel shave' THEN 'hot-towel-shave'
    WHEN 'Facials'         THEN 'facials'
    WHEN 'Waxing'          THEN 'waxing'
    WHEN 'Threading'       THEN 'threading'
    WHEN 'Chemical peels'  THEN 'chemical-peels'
    WHEN 'Microdermabrasion' THEN 'microdermabrasion'
    WHEN 'Lash brows'      THEN 'lash-brows'
    WHEN 'Brow lamination' THEN 'brow-lamination'
    ELSE lower(regexp_replace(value, '[^a-zA-Z0-9]+', '-', 'g'))
  END
  FROM unnest(specialties) AS value
)
WHERE cardinality(specialties) > 0;

-- Convert JobPost.specialty from display string to slug ID
UPDATE "JobPost"
SET specialty = CASE specialty
  WHEN 'Knotless braids' THEN 'knotless-braids'
  WHEN 'Box braids'      THEN 'box-braids'
  WHEN 'Feed-in braids'  THEN 'feed-in-braids'
  WHEN 'Cornrows'        THEN 'cornrows'
  WHEN 'Locs'            THEN 'locs'
  WHEN 'Faux locs'       THEN 'faux-locs'
  WHEN 'Loc maintenance' THEN 'loc-maintenance'
  WHEN 'Natural hair'    THEN 'natural-hair'
  WHEN 'Blowout'         THEN 'blowout'
  WHEN 'Silk press'      THEN 'silk-press'
  WHEN 'Relaxer'         THEN 'relaxer'
  WHEN 'Color'           THEN 'color'
  WHEN 'Balayage'        THEN 'balayage'
  WHEN 'Highlights'      THEN 'highlights'
  WHEN 'Weave/Sew-in'   THEN 'weave-sew-in'
  WHEN 'Wigs'            THEN 'wigs'
  WHEN 'Gel nails'       THEN 'gel-nails'
  WHEN 'Acrylic nails'   THEN 'acrylic-nails'
  WHEN 'Nail art'        THEN 'nail-art'
  WHEN 'Dip powder'      THEN 'dip-powder'
  WHEN 'Classic lashes'  THEN 'classic-lashes'
  WHEN 'Volume lashes'   THEN 'volume-lashes'
  WHEN 'Hybrid lashes'   THEN 'hybrid-lashes'
  WHEN 'Lash lift'       THEN 'lash-lift'
  WHEN 'Bridal makeup'   THEN 'bridal-makeup'
  WHEN 'Editorial makeup'THEN 'editorial-makeup'
  WHEN 'Airbrush makeup' THEN 'airbrush-makeup'
  WHEN 'Glam makeup'     THEN 'glam-makeup'
  WHEN 'SFX'             THEN 'sfx'
  WHEN 'Skin fade'       THEN 'fades'
  WHEN 'Fades'           THEN 'fades'
  WHEN 'Lineups'         THEN 'lineups'
  WHEN 'Beard trim'      THEN 'beard-trim'
  WHEN 'Beard design'    THEN 'beard-design'
  WHEN 'Kids cuts'       THEN 'kids-cuts'
  WHEN 'Facials'         THEN 'facials'
  WHEN 'Waxing'          THEN 'waxing'
  WHEN 'Threading'       THEN 'threading'
  ELSE lower(regexp_replace(specialty, '[^a-zA-Z0-9]+', '-', 'g'))
END
WHERE specialty IS NOT NULL;
