#!/usr/bin/env bash
# Build a local production Android App Bundle (AAB) and APK for SalonIn.
# Run from the repository root.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANDROID_DIR="$ROOT_DIR/apps/mobile/android"
CREDENTIALS_DIR="$ROOT_DIR/apps/mobile/credentials"

# Detect Android SDK
if [ -n "${ANDROID_HOME:-}" ]; then
  SDK_DIR="$ANDROID_HOME"
elif [ -n "${ANDROID_SDK_ROOT:-}" ]; then
  SDK_DIR="$ANDROID_SDK_ROOT"
elif [ -d "$HOME/Library/Android/sdk" ]; then
  SDK_DIR="$HOME/Library/Android/sdk"
elif [ -d "/usr/local/android-sdk" ]; then
  SDK_DIR="/usr/local/android-sdk"
elif [ -d "/opt/android-sdk" ]; then
  SDK_DIR="/opt/android-sdk"
else
  echo "Error: Android SDK not found. Set ANDROID_HOME or ANDROID_SDK_ROOT." >&2
  exit 1
fi

# Detect NDK (expected version 27.2.12479018)
NDK_VERSION="27.2.12479018"
if [ -d "$SDK_DIR/ndk/$NDK_VERSION" ]; then
  NDK_DIR="$SDK_DIR/ndk/$NDK_VERSION"
else
  echo "Warning: NDK $NDK_VERSION not found under $SDK_DIR/ndk" >&2
  NDK_DIR=""
fi

# Write local.properties
cat > "$ANDROID_DIR/local.properties" <<EOF
# Generated by scripts/build-android-release.sh
# This file is gitignored and should not be committed.
sdk.dir=$SDK_DIR
${NDK_DIR:+ndk.dir=$NDK_DIR}
EOF

echo "Android SDK: $SDK_DIR"
echo "Android NDK: ${NDK_DIR:-<not set>}"

# Ensure release keystore exists
if [ ! -f "$CREDENTIALS_DIR/salonin-release.keystore" ]; then
  echo "Error: Release keystore not found at $CREDENTIALS_DIR/salonin-release.keystore" >&2
  exit 1
fi

# Build production bundles
 cd "$ANDROID_DIR"

./gradlew clean bundleRelease assembleRelease

AAB_PATH="$ANDROID_DIR/app/build/outputs/bundle/release/app-release.aab"
APK_PATH="$ANDROID_DIR/app/build/outputs/apk/release/app-release.apk"

echo ""
echo "Build complete."
echo "AAB: $AAB_PATH"
echo "APK: $APK_PATH"
